### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by sana-ben036** [sana-ben036/brief-C2N3#1]
avoir une documentation suffisante pour utiliser les techniques et les technologies demandées afin d'atteindre l'objectif ( automatisation & organisation)

- [x] BEM et Spécificité
- [x] node-sass
- [x] node js
- [x] package management
- [x] positionnement

**Comment by youssefbm** [comment]
N'oubliez pas la partie de la spécificité, et pour nodejs npm node-sass jeter un coup d'oeil sur cette video : https://www.youtube.com/watch?v=yva2bj-lVRA

**Comment by sana-ben036** [comment]
documentation en général est faite

**Comment by youssefbm** [comment]
Well done you are progressing very well. Keep up.
