### ISSUE TITLE
le menu checkbox version mobile

### ISSUE THREAD

**Issue by sana-ben036** [sana-ben036/brief-C2N3#5]
j'ai un blocage au niveau de l'adaptation de  menu version mobile  .
la responsive ne fonctionne pas comme il faut 
et ce problème ça va m’empêcher de livrer mon travail au délai

**Comment by youssefbm** [comment]
Pas de problème, vous avez jusqu'à lundi inchallah.

**Comment by sana-ben036** [comment]
thank you, im doing my best

**Comment by sana-ben036** [comment]
le problème est reglé
